watsonAPI: "jiKBp0K2l1d-NU-4JMPnq07yHXDXF6O808saUJAOu7pB"

slackAPI: "https://hooks.slack.com/services/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"

TWILIO_API: "AC095d65393b5cb3530ceeb503e8d42eb9"

TWILIO_AUTH: "3def13f33e8de5589908cd875790cf96"

GOOGLE_API: "AIzaSyBps-kX8grkxiSLBr0Q7sKOL9Z2G9UwKWg"

DROPBOXAPI: "qaWo1RJdDUAAAAAAAAAAiuVLK_1vGY7r34oVIXzgk8fowWWuW41SEVEMqA5YRM2M"

sendgrid_api_key: "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"

zendesk_api_key: "VlqihFLYpPlg3G4SR9wAtFQw9bRUxR6btdgciYmT"

email: "severine.delpit@gmail.com"

phone_sender: "+15817056993"

phone_recipient: "+14185809201" #CHANGER POUR NUM Dun COACH

