watsonAPI: "jiKBp0K2l1d-NU-4JMPnq07yHXDXF6O808saUJAOu7pB"

slackAPI: "https://hooks.slack.com/services/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"

TWILIO_API: "AC095d65393b5cb3530ceeb503e8d42eb9"

TWILIO_AUTH: "3def13f33e8de5589908cd875790cf96"

GOOGLE_API: "AIzaSyBps-kX8grkxiSLBr0Q7sKOL9Z2G9UwKWg"

DROPBOXAPI: "qaWo1RJdDUAAAAAAAAAAiuVLK_1vGY7r34oVIXzgk8fowWWuW41SEVEMqA5YRM2M"

sendgrid_api_key: "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"

zendesk_api_key: "VlqihFLYpPlg3G4SR9wAtFQw9bRUxR6btdgciYmT"
